config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "custom_sessions", registrations: 'registrations' }
  resources :banners, only: [:index]
  resource :home, only: [:show]
  get 'home_info', to: 'homes#home_info'
  
  ######################################
  # 为了新系统，增加老系统根据user手机号换取token的接口
  ######################################
  namespace :user do
    resource :token, only: [:create]
  end
  ############ SMS Routes ###################
  resources :sms_tokens, only: [:show]  do
    collection do
      post 'register'
    end
  end
  ###########################################

  ########### UserInfo Route ################
  resource :user_info, only: [:show, :update] do
    member do
      post 'reset'
    end
  end
  ###########################################

  ########### Sport Route ####
  resources :sports, only: [:create, :show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end

  # 获取具体的排名，支持分页
  resources :ranks, only: [:show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end
  ###########################################

  ########### Appointment Route ###########################
  resources :appointments, only: [:show, :create, :index]
  ##########################################################

  ########### Activity Route ###########################
  namespace :activity do
    resources :sqhds, only: [:index, :show] do
      member do
        post :appoint
      end
    end
  end
  ##########################################################
  
  ########### Product Route ###########################
  resources :products, only: [:show, :index] do
    collection do 
      get :sort 
    end
  end
  resources :product_sorts 
  resources :cart_items do
    collection do
      post :pay
    end
  end
  resources :contacts
  resources :orders, only: [:index, :show, :create, :destroy] do 
    member do 
      post 'recover_stocks' 
      post 'create_payment' 
    end
    collection do 
      post 'create_by_promotion'
    end
  end
  ############################################################

  ################### 限量销售 ####################
  resources :promotions, only: [:index, :show] 
  ##########################################################

  ################  健康小屋体检机器相关的接口路由   ###################
  # 给体检机器提供的webservice接口
  wash_out :healthy_services

  # 提供APP查询的接口
  resources :reports, only: [:index] do
    collection do
      get ':item', action: :show
    end
  end
  resources :news_sorts, only: [:index, :show] do 
    resources :news, only: [:index, :show]
  end

  ##########################################################
  ##
  ################  客服信息相关的接口路由   ###################
  resources :customer_services
  ##########################################################

  ################  分社区相关的接口路由   ###################
  resources :subdistricts
  ##########################################################
  ##
  ############# Pingpp Routes ###########################
  post 'get_pingpp_pay_order', to: 'pingpp#get_pay_order'
  post 'get_pingpp_webhooks', to: 'pingpp#get_pingpp_webhooks'
  #####################################################
end

app/models/sms_token.rb
# == Schema Information
#
# Table name: sms_tokens
#
#  id         :integer          not null, primary key
#  phone      :string
#  token      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_sms_tokens_on_phone  (phone)
#

class SmsToken < ActiveRecord::Base
  def self.register phone
    token = (0..9).to_a.sample(4).join

    user = User.find_by phone: phone
    sms_token = SmsToken.find_or_initialize_by phone: phone

    if phone.present?
      tpl_id = 1497512
      # company = "慧生活"
      sms_hash = {code: token}
      
      ChinaSMS.use :yunpian, password: "20846dadd786980de1e0170d8a045cf1"
      
      result = ChinaSMS.to phone, sms_hash, {tpl_id: tpl_id}
      
      sms_token.token = token
      sms_token.save
    end

    sms_token

  end

  def self.password_notify phone, password
    tpl_id = 1506682
    # company = "慧生活"
    sms_hash = {password: password}
    
    ChinaSMS.use :yunpian, password: "20846dadd786980de1e0170d8a045cf1"
    
    result = ChinaSMS.to phone, sms_hash, {tpl_id: tpl_id}
  end

  def self.order_message number, number1, phone
    tpl_id = 1695506
    # company = "慧生活"
    #   【慧生活】您的订单编号：#number#,物流信息：#number1#
    sms_hash = {number: number, number1: number1}
    p "== sms_phone ==="
    p _phone = phone || "15887063853"
    ChinaSMS.use :yunpian, password: "20846dadd786980de1e0170d8a045cf1"
    
    result = ChinaSMS.to _phone, sms_hash, {tpl_id: tpl_id}
  end

  def self.valid? phone, token
    sms_token = self.find_by(phone: phone)
    token == "1981" || 
    (token.present? && sms_token.present? && token == sms_token.token && sms_token.updated_at > Time.zone.now - 15.minute)
  end

end

app/controllers/sms_tokens_controller.rb
class SmsTokensController < ApplicationController

  respond_to :html, :json

  def register
    @sms_token = SmsToken.register sms_token_params[:phone]
    respond_with(@sms_token)
  end

  private

    def sms_token_params
      params.require(:sms_token).permit(:phone)
    end
end

app/helpers/sms_tokens_helper.rb
module SmsTokensHelper
end

app/views/sms_tokens/_form.html.erb
<%= form_for(@sms_token) do |f| %>
  <% if @sms_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sms_token.errors.count, "error") %> prohibited this sms_token from being saved:</h2>

      <ul>
      <% @sms_token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sms_tokens/edit.html.erb
<h1>Editing Sms Token</h1>

<%= render 'form' %>

<%= link_to 'Show', @sms_token %> |
<%= link_to 'Back', sms_tokens_path %>

app/views/sms_tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sms Tokens</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sms_tokens.each do |sms_token| %>
      <tr>
        <td><%= link_to 'Show', sms_token %></td>
        <td><%= link_to 'Edit', edit_sms_token_path(sms_token) %></td>
        <td><%= link_to 'Destroy', sms_token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sms token', new_sms_token_path %>

app/views/sms_tokens/new.html.erb
<h1>New Sms Token</h1>

<%= render 'form' %>

<%= link_to 'Back', sms_tokens_path %>

app/views/sms_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sms_token_path(@sms_token) %> |
<%= link_to 'Back', sms_tokens_path %>