config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "custom_sessions", registrations: 'registrations' }
  resources :banners, only: [:index]
  resource :home, only: [:show]
  get 'home_info', to: 'homes#home_info'
  
  ######################################
  # 为了新系统，增加老系统根据user手机号换取token的接口
  ######################################
  namespace :user do
    resource :token, only: [:create]
  end
  ############ SMS Routes ###################
  resources :sms_tokens, only: [:show]  do
    collection do
      post 'register'
    end
  end
  ###########################################

  ########### UserInfo Route ################
  resource :user_info, only: [:show, :update] do
    member do
      post 'reset'
    end
  end
  ###########################################

  ########### Sport Route ####
  resources :sports, only: [:create, :show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end

  # 获取具体的排名，支持分页
  resources :ranks, only: [:show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end
  ###########################################

  ########### Appointment Route ###########################
  resources :appointments, only: [:show, :create, :index]
  ##########################################################

  ########### Activity Route ###########################
  namespace :activity do
    resources :sqhds, only: [:index, :show] do
      member do
        post :appoint
      end
    end
  end
  ##########################################################
  
  ########### Product Route ###########################
  resources :products, only: [:show, :index] do
    collection do 
      get :sort 
    end
  end
  resources :product_sorts 
  resources :cart_items do
    collection do
      post :pay
    end
  end
  resources :contacts
  resources :orders, only: [:index, :show, :create, :destroy] do 
    member do 
      post 'recover_stocks' 
      post 'create_payment' 
    end
    collection do 
      post 'create_by_promotion'
    end
  end
  ############################################################

  ################### 限量销售 ####################
  resources :promotions, only: [:index, :show] 
  ##########################################################

  ################  健康小屋体检机器相关的接口路由   ###################
  # 给体检机器提供的webservice接口
  wash_out :healthy_services

  # 提供APP查询的接口
  resources :reports, only: [:index] do
    collection do
      get ':item', action: :show
    end
  end
  resources :news_sorts, only: [:index, :show] do 
    resources :news, only: [:index, :show]
  end

  ##########################################################
  ##
  ################  客服信息相关的接口路由   ###################
  resources :customer_services
  ##########################################################

  ################  分社区相关的接口路由   ###################
  resources :subdistricts
  ##########################################################
  ##
  ############# Pingpp Routes ###########################
  post 'get_pingpp_pay_order', to: 'pingpp#get_pay_order'
  post 'get_pingpp_webhooks', to: 'pingpp#get_pingpp_webhooks'
  #####################################################
end

app/models/banner.rb
# == Schema Information
#
# Table name: banners
#
#  id             :integer          not null, primary key
#  title          :string
#  position       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  banner_type    :string
#  type_id        :integer
#  subdistrict_id :integer          default(1)
#

class Banner < ActiveRecord::Base
	default_scope {order("position")}
	
  has_one :banner_cover, -> { where photo_type: "banner_cover" }, class_name: "Image", as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :banner_cover, allow_destroy: true
  has_one :banner_detail, -> { where photo_type: "banner_detail" }, class_name: "Image", as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :banner_detail, allow_destroy: true
  
  belongs_to :subdistrict
  scope :subdistrict_is, ->(subdistrict_id){where(subdistrict_id: subdistrict_id)}
  scope :subdistrict_with_token, ->(token){where(subdistrict_id: token.nil? ? Subdistrict.first.id : User.where(authentication_token: token).first.subdistrict_id)}
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  # acts_as_token_authentication_handler_for User
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    # 没有鉴权的旧版默认显示社区Id为1内容
    @banners = Banner.subdistrict_with_token(request.headers.env["HTTP_X_USER_TOKEN"])
    respond_with(@banners)
  end

  def show
    respond_with(@banner)
  end

  def new
    @banner = Banner.new
    respond_with(@banner)
  end

  def edit
  end

  # def create
  #   @banner = Banner.subdistrict_with_token(request.headers.env["HTTP_X_USER_TOKEN"]).builde(banner_params)
  #   @banner.save
  #   respond_with(@banner)
  # end

  # def update
  #   @banner.update(banner_params)
  #   respond_with(@banner)
  # end

  # def destroy
  #   @banner.destroy
  #   respond_with(@banner)
  # end

  private
    def set_banner
      @banner = Banner.find(params[:id])
    end

    def banner_params
      params[:banner]
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_for(@banner) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Banners</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>