config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "custom_sessions", registrations: 'registrations' }
  resources :banners, only: [:index]
  resource :home, only: [:show]
  get 'home_info', to: 'homes#home_info'
  
  ######################################
  # 为了新系统，增加老系统根据user手机号换取token的接口
  ######################################
  namespace :user do
    resource :token, only: [:create]
  end
  ############ SMS Routes ###################
  resources :sms_tokens, only: [:show]  do
    collection do
      post 'register'
    end
  end
  ###########################################

  ########### UserInfo Route ################
  resource :user_info, only: [:show, :update] do
    member do
      post 'reset'
    end
  end
  ###########################################

  ########### Sport Route ####
  resources :sports, only: [:create, :show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end

  # 获取具体的排名，支持分页
  resources :ranks, only: [:show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end
  ###########################################

  ########### Appointment Route ###########################
  resources :appointments, only: [:show, :create, :index]
  ##########################################################

  ########### Activity Route ###########################
  namespace :activity do
    resources :sqhds, only: [:index, :show] do
      member do
        post :appoint
      end
    end
  end
  ##########################################################
  
  ########### Product Route ###########################
  resources :products, only: [:show, :index] do
    collection do 
      get :sort 
    end
  end
  resources :product_sorts 
  resources :cart_items do
    collection do
      post :pay
    end
  end
  resources :contacts
  resources :orders, only: [:index, :show, :create, :destroy] do 
    member do 
      post 'recover_stocks' 
      post 'create_payment' 
    end
    collection do 
      post 'create_by_promotion'
    end
  end
  ############################################################

  ################### 限量销售 ####################
  resources :promotions, only: [:index, :show] 
  ##########################################################

  ################  健康小屋体检机器相关的接口路由   ###################
  # 给体检机器提供的webservice接口
  wash_out :healthy_services

  # 提供APP查询的接口
  resources :reports, only: [:index] do
    collection do
      get ':item', action: :show
    end
  end
  resources :news_sorts, only: [:index, :show] do 
    resources :news, only: [:index, :show]
  end

  ##########################################################
  ##
  ################  客服信息相关的接口路由   ###################
  resources :customer_services
  ##########################################################

  ################  分社区相关的接口路由   ###################
  resources :subdistricts
  ##########################################################
  ##
  ############# Pingpp Routes ###########################
  post 'get_pingpp_pay_order', to: 'pingpp#get_pay_order'
  post 'get_pingpp_webhooks', to: 'pingpp#get_pingpp_webhooks'
  #####################################################
end

app/models/news_sort.rb
# == Schema Information
#
# Table name: news_sorts
#
#  id             :integer          not null, primary key
#  rank           :integer
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  subdistrict_id :integer
#

class NewsSort < ActiveRecord::Base
	has_many :news

	has_one :news_sort_cover, -> { where photo_type: "news_sort_cover" }, class_name: "Image", as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :news_sort_cover, allow_destroy: true

  default_scope {order(:rank)}
  scope :title_is, -> (title) { where(title: title)}

end

app/controllers/news_sorts_controller.rb
class NewsSortsController < ApplicationController
  acts_as_token_authentication_handler_for User
  before_action :set_news_sort, only: [:show, :edit, :update, :destroy]

  respond_to :json

  def index
    @news_sorts = NewsSort.all
    respond_with(@news_sorts)
  end

  def show
    respond_with(@news_sort)
  end

  def new
    @news_sort = NewsSort.new
    respond_with(@news_sort)
  end

  def edit
  end

  def create
    @news_sort = NewsSort.new(news_sort_params)
    @news_sort.save
    respond_with(@news_sort)
  end

  def update
    @news_sort.update(news_sort_params)
    respond_with(@news_sort)
  end

  def destroy
    @news_sort.destroy
    respond_with(@news_sort)
  end

  private
    def set_news_sort
      @news_sort = NewsSort.find(params[:id])
    end

    def news_sort_params
      params[:news_sort]
    end
end

app/helpers/news_sorts_helper.rb
module NewsSortsHelper
end

app/views/news_sorts/_form.html.erb
<%= form_for(@news_sort) do |f| %>
  <% if @news_sort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_sort.errors.count, "error") %> prohibited this news_sort from being saved:</h2>

      <ul>
      <% @news_sort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_sorts/edit.html.erb
<h1>Editing News Sort</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_sort %> |
<%= link_to 'Back', news_sorts_path %>

app/views/news_sorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Sorts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_sorts.each do |news_sort| %>
      <tr>
        <td><%= link_to 'Show', news_sort %></td>
        <td><%= link_to 'Edit', edit_news_sort_path(news_sort) %></td>
        <td><%= link_to 'Destroy', news_sort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News sort', new_news_sort_path %>

app/views/news_sorts/new.html.erb
<h1>New News Sort</h1>

<%= render 'form' %>

<%= link_to 'Back', news_sorts_path %>

app/views/news_sorts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_news_sort_path(@news_sort) %> |
<%= link_to 'Back', news_sorts_path %>