config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "custom_sessions", registrations: 'registrations' }
  resources :banners, only: [:index]
  resource :home, only: [:show]
  get 'home_info', to: 'homes#home_info'
  
  ######################################
  # 为了新系统，增加老系统根据user手机号换取token的接口
  ######################################
  namespace :user do
    resource :token, only: [:create]
  end
  ############ SMS Routes ###################
  resources :sms_tokens, only: [:show]  do
    collection do
      post 'register'
    end
  end
  ###########################################

  ########### UserInfo Route ################
  resource :user_info, only: [:show, :update] do
    member do
      post 'reset'
    end
  end
  ###########################################

  ########### Sport Route ####
  resources :sports, only: [:create, :show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end

  # 获取具体的排名，支持分页
  resources :ranks, only: [:show] do
    collection do
      get 'daily'
      get 'weekly'
      get 'monthly'
      get 'yearly'
    end
  end
  ###########################################

  ########### Appointment Route ###########################
  resources :appointments, only: [:show, :create, :index]
  ##########################################################

  ########### Activity Route ###########################
  namespace :activity do
    resources :sqhds, only: [:index, :show] do
      member do
        post :appoint
      end
    end
  end
  ##########################################################
  
  ########### Product Route ###########################
  resources :products, only: [:show, :index] do
    collection do 
      get :sort 
    end
  end
  resources :product_sorts 
  resources :cart_items do
    collection do
      post :pay
    end
  end
  resources :contacts
  resources :orders, only: [:index, :show, :create, :destroy] do 
    member do 
      post 'recover_stocks' 
      post 'create_payment' 
    end
    collection do 
      post 'create_by_promotion'
    end
  end
  ############################################################

  ################### 限量销售 ####################
  resources :promotions, only: [:index, :show] 
  ##########################################################

  ################  健康小屋体检机器相关的接口路由   ###################
  # 给体检机器提供的webservice接口
  wash_out :healthy_services

  # 提供APP查询的接口
  resources :reports, only: [:index] do
    collection do
      get ':item', action: :show
    end
  end
  resources :news_sorts, only: [:index, :show] do 
    resources :news, only: [:index, :show]
  end

  ##########################################################
  ##
  ################  客服信息相关的接口路由   ###################
  resources :customer_services
  ##########################################################

  ################  分社区相关的接口路由   ###################
  resources :subdistricts
  ##########################################################
  ##
  ############# Pingpp Routes ###########################
  post 'get_pingpp_pay_order', to: 'pingpp#get_pay_order'
  post 'get_pingpp_webhooks', to: 'pingpp#get_pingpp_webhooks'
  #####################################################
end

app/models/customer_service.rb
# == Schema Information
#
# Table name: customer_services
#
#  id             :integer          not null, primary key
#  name           :string
#  phone          :string
#  subdistrict_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_customer_services_on_subdistrict_id  (subdistrict_id)
#

class CustomerService < ActiveRecord::Base
	scope :subdistrict_is, ->(id){where(subdistrict_id: id)}
end

app/controllers/customer_services_controller.rb
class CustomerServicesController < ApplicationController
  acts_as_token_authentication_handler_for User 
  before_action :set_customer_service, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @customer_services = CustomerService.subdistrict_is(current_user.subdistrict_id)
    respond_with(@customer_services)
  end

  def show
    respond_with(@customer_service)
  end

  # def new
  #   @customer_service = CustomerService.new
  #   respond_with(@customer_service)
  # end

  # def edit
  # end

  # def create
  #   @customer_service = CustomerService.new(customer_service_params)
  #   @customer_service.save
  #   respond_with(@customer_service)
  # end

  # def update
  #   @customer_service.update(customer_service_params)
  #   respond_with(@customer_service)
  # end

  # def destroy
  #   @customer_service.destroy
  #   respond_with(@customer_service)
  # end

  private
    def set_customer_service
      @customer_service = CustomerService.find(params[:id])
    end

    def customer_service_params
      params[:customer_service]
    end
end

app/helpers/customer_services_helper.rb
module CustomerServicesHelper
end

app/views/customer_services/_form.html.erb
<%= form_for(@customer_service) do |f| %>
  <% if @customer_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_service.errors.count, "error") %> prohibited this customer_service from being saved:</h2>

      <ul>
      <% @customer_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_services/edit.html.erb
<h1>Editing Customer Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_service %> |
<%= link_to 'Back', customer_services_path %>

app/views/customer_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customer Services</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_services.each do |customer_service| %>
      <tr>
        <td><%= link_to 'Show', customer_service %></td>
        <td><%= link_to 'Edit', edit_customer_service_path(customer_service) %></td>
        <td><%= link_to 'Destroy', customer_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer service', new_customer_service_path %>

app/views/customer_services/new.html.erb
<h1>New Customer Service</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_services_path %>

app/views/customer_services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_service_path(@customer_service) %> |
<%= link_to 'Back', customer_services_path %>